### ISSUE TITLE
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

### ISSUE THREAD

**Issue by NaeemKhan333** [MrinalJain17/Human-Activity-Recognition#10]
Traceback (most recent call last):
  File "human_activity_recognition.py", line 204, in <module>
    X_train = reader.read_videos(train_files)
  File "/home/user/Documents/ActivityRecognition/Methods/3rd/Human-Activity-Recognition-master/utils.py", line 70, in read_videos
    self._read_video(path) for path in tqdm(paths)
  File "/home/user/Documents/ActivityRecognition/Methods/3rd/Human-Activity-Recognition-master/utils.py", line 70, in <listcomp>
    self._read_video(path) for path in tqdm(paths)
  File "/home/user/Documents/ActivityRecognition/Methods/3rd/Human-Activity-Recognition-master/utils.py", line 126, in _read_video
    cap = FFmpegReader(filename=path)
  File "/home/user/anaconda3/lib/python3.7/site-packages/skvideo/io/ffmpeg.py", line 130, in __init__
    raise ValueError("No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.
 50%|████████████████████▋                    | 151/300 [02:39<02:37,  1.06s/it]

**Comment by MrinalJain17** [comment]
Chances are, you did not delete one of the corrupted videos present in the dataset. More info in **instruction no. 3** in the README.
